language: node_js
node_js:
  - '0.8'
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-rnvmedia' ]; then cd .. && eval "mv $currentfolder generator-rnvmedia" && cd generator-rnvmedia; fi

